import type {
  AboutPageContent,
  AutoRepairPageContent,
  ContactPageContent,
  FaqPageContent,
  FleetPageContent,
  GalleryPageContent,
  GiftCardsPageContent,
  HomePageContent,
  NavigationContent,
  PricingPageContent,
  SiteSettingsContent,
  ServicesPageContent,
} from '../types/cms';

export const defaultHomePageContent: HomePageContent = {
  heroTitle: "Ontario's Top",
  heroAccent: 'Ceramic Coating',
  heroSubtitle: "Preserve Your Paint | Enhance Your Car's Value | Drive with Confidence",
  heroImage: '/client-images/hero-section-pic.PNG',
  heroButtonLabel: 'Get Started',
  heroButtonPath: '/booking',
  whyTitle: 'Why Choose Us?',
  whyBody:
    'Spa for Cars specializes in high-quality car detailing that restores, protects, and enhances your vehicle. We are your one-stop shop for deep interior cleaning, exterior polishing, long-lasting ceramic coating, PPF, window tinting, and much more!',
  whyFeatures: [
    {
      icon: 'shield',
      title: 'Ceramic Coating',
      description: 'Industry-leading 9H ceramic protection that lasts years, not months.',
    },
    {
      icon: 'droplets',
      title: 'Paint Correction',
      description: 'Multi-stage paint correction to eliminate swirls, scratches and oxidation.',
    },
    {
      icon: 'car',
      title: 'Full Detailing',
      description: 'Comprehensive interior and exterior detailing for a showroom finish.',
    },
    {
      icon: 'sparkles',
      title: 'Window Tinting',
      description: 'Premium window tinting for UV protection, privacy, and style.',
    },
  ],
  showcaseBadge: 'Our Services',
  showcaseTitle: 'What We Offer',
  showcaseViewAllLabel: 'View All',
  showcaseViewAllPath: '/services',
  showcaseServices: [],
  testimonialQuote:
    '"My Tesla has never looked this good. The ceramic coating is a game changer. Pure art."',
  testimonialAuthor: '- Alex Johnson, Tesla Model S Owner',
  galleryBadge: 'Our Work',
  galleryTitle: 'Recent Projects',
  galleryViewAllLabel: 'View Full Gallery',
  galleryViewAllPath: '/gallery',
  galleryImages: [
    '/client-images/IMG_2414.PNG',
    '/client-images/IMG_2449.PNG',
    '/client-images/IMG_2462.PNG',
  ],
  ctaTitle: 'Ready to Transform Your Vehicle?',
  ctaBody: 'Book your appointment today and experience the Spa for Cars difference.',
  ctaButtonLabel: 'Book Appointment',
  ctaButtonPath: '/booking',
  promoPlacements: [],
};

export const defaultServicesPageContent: ServicesPageContent = {
  badge: 'Service Menu',
  title: 'Professional Auto Detailing & Vehicle Care Services',
  subtitle:
    'Exact service offerings, package inclusions, and standalone service pricing based on the current Spa 4 Cars service menus.',
  detailingPackagesTitle: 'Auto Detailing Packages',
  detailingOfferings: [
    {
      id: 'full-detail-standard-cars',
      title: 'Full Detail - Sedan / Coupe / Standard Cars',
      shortTitle: 'Full Detail',
      description:
        'Complete interior and exterior detailing package sized for sedans, coupes, and standard cars.',
      category: 'detailing',
      priceLabel: '$250',
      fixedPriceAmount: 250,
      duration: '3-5 Hours',
      image: '/client-images/IMG_2461.PNG',
      features: ['Exterior detailing package', 'Interior detailing package', 'Vehicle-size priced'],
      notes: 'Includes the full exterior and interior detailing inclusions listed below.',
      bookable: true,
      addOnOnly: false,
    },
    {
      id: 'interior-only-standard-cars',
      title: 'Interior Only - Sedan / Coupe / Standard Cars',
      shortTitle: 'Interior Only',
      description:
        'Deep interior restoration package sized for sedans, coupes, and standard cars.',
      category: 'detailing',
      priceLabel: '$200',
      fixedPriceAmount: 200,
      duration: '2.5-4 Hours',
      image: '/client-images/IMG_2460_after.PNG',
      features: ['Interior detailing package', 'Vehicle-size priced', 'Seats, carpets, mats, and trim'],
      notes: 'Focused on interior surfaces, upholstery, carpets, vents, and windows.',
      bookable: true,
      addOnOnly: false,
    },
    {
      id: 'full-detail-standard-suv',
      title: 'Full Detail - Standard Size SUV',
      shortTitle: 'Full Detail',
      description: 'Complete interior and exterior detailing package sized for standard SUVs.',
      category: 'detailing',
      priceLabel: '$275',
      fixedPriceAmount: 275,
      duration: '4-6 Hours',
      image: '/client-images/IMG_2414.PNG',
      features: ['Exterior detailing package', 'Interior detailing package', 'Vehicle-size priced'],
      notes: 'Includes the full exterior and interior detailing inclusions listed below.',
      bookable: true,
      addOnOnly: false,
    },
    {
      id: 'interior-only-standard-suv',
      title: 'Interior Only - Standard Size SUV',
      shortTitle: 'Interior Only',
      description: 'Deep interior restoration package sized for standard SUVs.',
      category: 'detailing',
      priceLabel: '$225',
      fixedPriceAmount: 225,
      duration: '3-4.5 Hours',
      image: '/client-images/IMG_2460_before.PNG',
      features: ['Interior detailing package', 'Vehicle-size priced', 'Seats, carpets, mats, and trim'],
      notes: 'Focused on interior surfaces, upholstery, carpets, vents, and windows.',
      bookable: true,
      addOnOnly: false,
    },
    {
      id: 'full-detail-large-suv',
      title: 'Full Detail - Large SUV / Large Vehicles',
      shortTitle: 'Full Detail',
      description:
        'Complete interior and exterior detailing package sized for large SUVs and larger vehicles.',
      category: 'detailing',
      priceLabel: '$315',
      fixedPriceAmount: 315,
      duration: '4.5-6.5 Hours',
      image: '/client-images/IMG_2417.PNG',
      features: ['Exterior detailing package', 'Interior detailing package', 'Vehicle-size priced'],
      notes: 'Includes the full exterior and interior detailing inclusions listed below.',
      bookable: true,
      addOnOnly: false,
    },
    {
      id: 'interior-only-large-suv',
      title: 'Interior Only - Large SUV / Large Vehicles',
      shortTitle: 'Interior Only',
      description:
        'Deep interior restoration package sized for large SUVs and larger vehicles.',
      category: 'detailing',
      priceLabel: '$275',
      fixedPriceAmount: 275,
      duration: '3.5-5 Hours',
      image: '/client-images/IMG_2445_after.PNG',
      features: ['Interior detailing package', 'Vehicle-size priced', 'Seats, carpets, mats, and trim'],
      notes: 'Focused on interior surfaces, upholstery, carpets, vents, and windows.',
      bookable: true,
      addOnOnly: false,
    },
  ],
  detailingPackages: [
    {
      vehicleType: 'Sedan / Coupe / Standard Cars',
      fullDetailId: 'full-detail-standard-cars',
      interiorOnlyId: 'interior-only-standard-cars',
    },
    {
      vehicleType: 'Standard Size SUV',
      fullDetailId: 'full-detail-standard-suv',
      interiorOnlyId: 'interior-only-standard-suv',
    },
    {
      vehicleType: 'Large SUV / Large Vehicles',
      fullDetailId: 'full-detail-large-suv',
      interiorOnlyId: 'interior-only-large-suv',
    },
  ],
  exteriorIncludesTitle: 'Exterior Detailing Includes',
  exteriorIncludes: [
    'Hand wash and dry',
    'Foam pre-soak',
    'Bug and tar removal',
    'Wheel and rim deep cleaning',
    'Tire cleaning and dressing',
    'Door jamb cleaning',
    'Exterior window cleaning',
    'Paint decontamination (iron remover / clay bar)',
    'Wax or paint sealant application',
    'Trim and plastic dressing',
    'Emblem and badge detailing',
    'Final exterior inspection',
  ],
  interiorIncludesTitle: 'Interior Detailing Includes',
  interiorIncludes: [
    'Full interior vacuum (seats, carpets, mats, trunk)',
    'Carpet and floor mat shampoo',
    'Upholstery cleaning (fabric or leather)',
    'Leather cleaning and conditioning',
    'Dashboard, console, and panel cleaning',
    'Interior plastic and vinyl conditioning',
    'Air vent cleaning',
    'Door panels and pockets cleaned',
    'Cup holders and crevices cleaned',
    'Interior windows and mirrors cleaned',
  ],
  specialtyServicesTitle: 'Specialty Services',
  specialtyServices: [
    {
      id: 'wash-and-wax',
      title: 'Wash & Wax',
      shortTitle: 'Wash & Wax',
      description:
        'Maintenance-focused exterior refresh with foam treatment, wheel cleaning, and paint protection.',
      category: 'maintenance',
      priceLabel: '$100 - $130',
      duration: 'By vehicle size',
      image: '/client-images/IMG_2414.PNG',
      features: [
        'Hand wash',
        'Foam treatment',
        'Wheel and rim cleaning',
        'Tire cleaning',
        'Wax application for paint protection',
        'Exterior shine finishing',
      ],
      notes: 'Pricing varies by vehicle size.',
      bookable: true,
      addOnOnly: false,
    },
    {
      id: 'ceramic-coating',
      title: 'Ceramic Coating',
      shortTitle: 'Ceramic Coating',
      description:
        'Professional ceramic coating application for long-term paint protection and easier maintenance.',
      category: 'protection',
      priceLabel: '$400 - $600 (3 Year Warranty)',
      duration: '1 Day',
      image: '/client-images/IMG_2449.PNG',
      features: [
        'Professional ceramic coating application',
        'Long-term paint protection',
        'High gloss finish',
        'UV and chemical resistance',
        'Hydrophobic water-repellent surface',
      ],
      notes: 'Pricing varies by vehicle size and includes a 3-year warranty.',
      bookable: true,
      addOnOnly: false,
    },
    {
      id: 'window-tint-complete-vehicle',
      title: 'Window Tinting - Complete Vehicle (4 Doors)',
      shortTitle: 'Window Tinting',
      description:
        'Complete vehicle window tint installation for privacy, cabin protection, and a cleaner finish.',
      category: 'tint',
      priceLabel: '$300',
      fixedPriceAmount: 300,
      duration: '4-6 Hours',
      image: '/client-images/IMG_2421_after.PNG',
      features: [
        'Professional installation',
        'Heat and UV rejection',
        'Interior protection from sun damage',
        'Increased privacy',
        'Multiple tint shades available',
      ],
      notes: 'Covers a complete vehicle with 4 doors.',
      bookable: true,
      addOnOnly: false,
    },
    {
      id: 'window-tint-two-front',
      title: 'Window Tinting - Two Front Windows',
      shortTitle: 'Window Tinting',
      description:
        'Front-window tint package for drivers who want a lighter privacy and heat-reduction upgrade.',
      category: 'tint',
      priceLabel: '$150',
      fixedPriceAmount: 150,
      duration: '1-2 Hours',
      image: '/client-images/IMG_2421_before.PNG',
      features: [
        'Professional installation',
        'Heat and UV rejection',
        'Interior protection from sun damage',
        'Increased privacy',
        'Multiple tint shades available',
      ],
      notes: 'Covers the two front windows only.',
      bookable: true,
      addOnOnly: false,
    },
    {
      id: 'paint-restoration',
      title: 'Paint Restoration',
      shortTitle: 'Paint Restoration',
      description:
        'Polishing and buffing service designed to improve gloss and reduce visible paint defects.',
      category: 'restoration',
      priceLabel: 'Starting at $600',
      duration: 'By assessment',
      image: '/client-images/IMG_2418_after.PNG',
      features: [
        'Polishing and buffing',
        'Scratch-condition dependent scope',
        'Vehicle-size dependent pricing',
      ],
      notes: 'Final scope depends on vehicle size and scratch condition.',
      bookable: true,
      addOnOnly: false,
    },
  ],
  additionalServicesTitle: 'Additional Services',
  additionalServices: [
    {
      id: 'headlight-restoration',
      title: 'Headlight Restoration',
      shortTitle: 'Headlight Restoration',
      description: 'Restore cloudy headlights for improved clarity and a cleaner front-end appearance.',
      category: 'add_on',
      priceLabel: '$100 (2 Year Warranty)',
      fixedPriceAmount: 100,
      duration: '1-2 Hours',
      image: '/client-images/IMG_2415.PNG',
      features: ['Surface restoration', 'Improved clarity', '2 year warranty'],
      notes: 'Available as a standalone booked service.',
      bookable: true,
      addOnOnly: false,
    },
    {
      id: 'engine-bay-cleaning',
      title: 'Engine Bay Cleaning',
      shortTitle: 'Engine Bay Cleaning',
      description: 'Degrease and refresh the engine bay for a cleaner under-hood presentation.',
      category: 'add_on',
      priceLabel: '$75',
      fixedPriceAmount: 75,
      duration: '45-60 min',
      image: '/client-images/IMG_2417.PNG',
      features: ['Degreasing', 'Detail cleaning', 'Presentation-focused finish'],
      notes: 'Available as a standalone booked service.',
      bookable: true,
      addOnOnly: false,
    },
    {
      id: 'pet-hair-removal',
      title: 'Pet Hair Removal',
      shortTitle: 'Pet Hair Removal',
      description: 'Deep interior labor service for embedded pet hair in seats, carpets, and mats.',
      category: 'add_on',
      priceLabel: 'Price depends on severity',
      duration: 'By assessment',
      image: '/client-images/IMG_2445_before.PNG',
      features: ['Severity-based labor', 'Seat and carpet focus', 'Interior detailing support'],
      notes: 'Pricing depends on severity and is quoted after assessment.',
      bookable: true,
      addOnOnly: false,
    },
    {
      id: 'odor-removal',
      title: 'Odor Removal',
      shortTitle: 'Odor Removal',
      description: 'Targeted odor-treatment service for smoke, spills, moisture, and persistent cabin smells.',
      category: 'add_on',
      priceLabel: '$100',
      fixedPriceAmount: 100,
      duration: 'Approx. 6-7 Hours',
      image: '/client-images/IMG_2460_after.PNG',
      features: ['Odor treatment', 'Approx. 6-7 hour process', 'Interior-focused remediation'],
      notes: 'Available as a standalone booked service.',
      bookable: true,
      addOnOnly: false,
    },
    {
      id: 'brake-caliper-painting',
      title: 'Brake Caliper Painting (4)',
      shortTitle: 'Brake Caliper Painting',
      description: 'Four-caliper refinishing service that adds a clean, custom accent to the vehicle.',
      category: 'add_on',
      priceLabel: '$700 (2 Year Warranty)',
      fixedPriceAmount: 700,
      duration: '1 Day',
      image: '/client-images/IMG_2439_after.PNG',
      features: ['Four-caliper service', 'Custom finish', '2 year warranty'],
      notes: 'Available as a standalone booked service.',
      bookable: true,
      addOnOnly: false,
    },
  ],
  featuredOfferingIds: [
    'full-detail-standard-cars',
    'ceramic-coating',
    'window-tint-complete-vehicle',
  ],
};

export const defaultFleetPageContent: FleetPageContent = {
  badge: 'Commercial Programs',
  title: 'Premium Detailing for Private Owners & Commercial Fleets',
  subtitle:
    'We deliver consistent turnaround, clean reporting, and scalable service plans for businesses that need vehicle presentation standards maintained.',
  dealershipsTitle: 'Dealerships',
  dealershipsItems: [
    'Pre-delivery inspection detailing',
    'Lot maintenance wash scheduling',
    'Showroom finish enhancement',
    'Priority turnaround windows',
  ],
  fleetsTitle: 'Corporate Fleets',
  fleetsItems: [
    'Monthly or bi-weekly service plans',
    'Consolidated invoicing',
    'On-site and studio service options',
    'Executive vehicle care tiers',
  ],
  proposalTitle: 'Request Proposal',
  proposalSubtitle:
    'Share your monthly volume and service expectations. We will provide a tailored plan and pricing recommendation.',
};

export const defaultFaqPageContent: FaqPageContent = {
  items: [
    {
      question: 'How long does a full detail take?',
      answer:
        'A standard full detail typically takes 3-5 hours depending on vehicle size and condition. Ceramic coating packages may require 24-48 hours for proper prep and curing.',
    },
    {
      question: 'Do you offer mobile detailing?',
      answer:
        'Yes. We offer mobile service for fleet clients and selected premium packages. Paint correction and ceramic coatings are best completed in our controlled studio environment.',
    },
    {
      question: 'What is the difference between wax and ceramic coating?',
      answer:
        'Wax sits on top of the paint and usually lasts 1-3 months. Ceramic coating bonds to the surface and provides longer protection, stronger chemical resistance, and easier maintenance.',
    },
    {
      question: 'How should I maintain my car after a coating?',
      answer:
        'Avoid brush-based automatic washes. Use pH-neutral soap and proper hand-wash technique. We provide a full aftercare guide with every coating package.',
    },
    {
      question: 'Is there a cancellation fee?',
      answer:
        'We request at least 24 hours notice. Cancellations within 24 hours may be subject to a $50 fee.',
    },
  ],
};

export const defaultContactPageContent: ContactPageContent = {
  title: 'Talk To Our Team',
  subtitle: 'Send us your request and we will get back with recommendations, pricing, and next steps.',
  address: 'Aurora, Ontario\nGreater Toronto Area',
  mapEmbedUrl: 'https://www.google.com/maps?q=Aurora%2C%20Ontario&output=embed',
};

export const defaultAboutPageContent: AboutPageContent = {
  badge: 'Our Story',
  title: 'More Than Just A Wash',
  subtitle:
    'Spa for Cars was founded to give every vehicle the same level of detail and care usually reserved for showroom exotics.',
  image: '/client-images/IMG_2417.PNG',
  imageBadge: 'Est. 2018',
  evolutionTitle: 'The Evolution',
  evolutionBody:
    'Formerly known as Quick Shine Auto, we grew into a process-driven studio focused on lasting protection, not quick cosmetics. The name Spa for Cars reflects the same careful treatment and restoration mindset we apply to every vehicle.',
  valueCards: [
    {
      icon: 'award',
      title: 'Certified Pros',
      description: 'IDA-certified detailers with disciplined prep and finish standards.',
    },
    {
      icon: 'heart',
      title: 'Passion Driven',
      description: 'We treat daily drivers and high-performance cars with the same care.',
    },
    {
      icon: 'users',
      title: 'Client First',
      description:
        'Transparent recommendations, realistic timelines, and clear communication from drop-off to handover.',
    },
  ],
};

export const defaultGalleryPageContent: GalleryPageContent = {
  badge: 'Real Results',
  title: 'Before And After Transformations',
  subtitle: 'Drag each slider to compare real customer vehicles before and after service.',
  transformations: [
    {
      label: 'Paint Correction',
      beforeImage: '/client-images/IMG_2414.PNG',
      afterImage: '/client-images/IMG_2415.PNG',
    },
    {
      label: 'Interior Restoration',
      beforeImage: '/client-images/IMG_2460_before.PNG',
      afterImage: '/client-images/IMG_2460_after.PNG',
    },
    {
      label: 'Steering Restoration',
      beforeImage: '/client-images/IMG_2439_before.PNG',
      afterImage: '/client-images/IMG_2439_after.PNG',
    },
    {
      label: 'Leather Seat Restoration',
      beforeImage: '/client-images/IMG_2445_before.PNG',
      afterImage: '/client-images/IMG_2445_after.PNG',
    },
    {
      label: 'Trim Refinement',
      beforeImage: '/client-images/IMG_2421_before.PNG',
      afterImage: '/client-images/IMG_2421_after.PNG',
    },
    {
      label: 'Panel Correction',
      beforeImage: '/client-images/IMG_2418_before.PNG',
      afterImage: '/client-images/IMG_2418_after.PNG',
    },
  ],
};

export const defaultAutoRepairPageContent: AutoRepairPageContent = {
  badge: 'New Service Division',
  title: 'Auto Repair Coming Soon',
  subtitle:
    'We are building a dedicated repair program to pair mechanical reliability with the same premium detailing standards.',
  inputPlaceholder: 'Enter your email for updates',
  submitButtonLabel: 'Notify Me',
  submittingButtonLabel: 'Submitting...',
  successTitle: "You're on the list",
  successMessage: "We'll notify you as soon as bookings open.",
};

export const defaultGiftCardsPageContent: GiftCardsPageContent = {
  badge: 'Gift Cards',
  title: 'Send Premium Vehicle Care As A Gift',
  subtitle: 'Digital gift cards are delivered instantly and can be used for any Spa for Cars service.',
  cardBrand: 'Spa for Cars',
  cardTitle: 'Gift Card',
  cardTagline: 'Valid on all detailing and protection services',
  benefits: [
    'Instant digital delivery by email',
    'No expiry date',
    'Redeemable across all services',
    'Great for enthusiasts and new car owners',
  ],
  configureTitle: 'Configure Gift Card',
  presetAmounts: [50, 100, 200, 300, 500],
  minCustomAmount: 25,
  recipientEmailLabel: 'Recipient Email',
  senderNameLabel: 'From',
  messageLabel: 'Message',
  proceedButtonLabel: 'Proceed To Payment',
  proceedingButtonLabel: 'Preparing Payment...',
  paymentTitle: 'Secure Payment',
  backToConfigLabel: 'Back',
  paymentNote: 'Secure checkout powered by Stripe.',
  successTitle: 'Purchase Complete',
  successMessagePrefix: 'Your gift card has been sent to',
  resetButtonLabel: 'Send Another Gift Card',
};

export const defaultPricingPageContent: PricingPageContent = {
  badge: 'Transparent Pricing',
  title: 'Premium Care Without Hidden Fees',
  subtitle:
    'Choose a package based on your vehicle condition and finish expectations. We can always tailor from here.',
  mostPopularBadge: 'Most Popular',
  selectPlanLabel: 'Select Plan',
  customQuoteTitle: 'Need A Custom Scope?',
  customQuoteBody:
    'For fleet contracts, restoration projects, or unique vehicles, we can build a custom plan around your needs.',
  customQuoteButtonLabel: 'Request Custom Quote',
  customQuoteButtonPath: '/contact',
  highlightServiceId: 'ceramic-coating',
};

export const defaultNavigationContent: NavigationContent = {
  primaryLinks: [
    { label: 'Home', path: '/', enabled: true },
    { label: 'Services', path: '/services', enabled: true },
    { label: 'Repair', path: '/auto-repair', enabled: true },
    { label: 'Showcase', path: '/gallery', enabled: true },
    { label: 'Fleet', path: '/fleet', enabled: true },
    { label: 'About', path: '/about', enabled: true },
    { label: 'Contact', path: '/contact', enabled: true },
  ],
  secondaryLinks: [
    { label: 'FAQ', path: '/faq', enabled: true },
    { label: 'Gift Cards', path: '/gift-cards', enabled: true },
    { label: 'Dashboard', path: '/dashboard', enabled: true },
    { label: 'Admin', path: '/admin', enabled: true },
  ],
  bookingCtaLabel: 'Book Now',
  bookingCtaPath: '/booking',
};

export const defaultSiteSettingsContent: SiteSettingsContent = {
  businessName: 'Spa for Cars',
  serviceNotice: 'Complimentary pick-up & drop off available (within close radius of the store only)',
  contactEmail: 'info@spaforcars.ca',
  contactPhone: '(416) 986-4746',
  topBarHours: 'Mon-Sat 8:00 AM - 6:00 PM',
  address: 'Aurora, Ontario',
  instagramUrl: 'https://www.instagram.com',
  tiktokUrl: 'https://www.tiktok.com',
  footerTagline: 'Designed for premium automotive care',
};
